export const MITIGATION_CATALOGUE_FETCH_ALL = 'MITIGATION_CATALOGUE_FETCH_ALL';
export const MITIGATION_CATALOGUE_FETCH_BY_ID = 'MITIGATION_CATALOGUE_FETCH_BY_ID';
export const MITIGATION_CATALOGUE_CLEAR = 'MITIGATION_CATALOGUE_CLEAR';
export const MITIGATION_CATALOGUE_CREATE = 'MITIGATION_CATALOGUE_CREATE';
export const MITIGATION_CATALOGUE_UPDATE = 'MITIGATION_CATALOGUE_UPDATE';
export const MITIGATION_CATALOGUE_DELETE = 'MITIGATION_CATALOGUE_DELETE';
export const MITIGATION_CATALOGUE_BOOTSTRAP = 'MITIGATION_CATALOGUE_BOOTSTRAP';
export const MITIGATION_CATALOGUE_SET_MITIGATIONS = 'MITIGATION_CATALOGUE_SET_MITIGATIONS';
export const MITIGATION_CATALOGUE_SET_STORE_STATUS = 'MITIGATION_CATALOGUE_SET_STORE_STATUS';
export const MITIGATION_CATALOGUE_EXPORT = 'MITIGATION_CATALOGUE_EXPORT';
export const MITIGATION_CATALOGUE_IMPORT = 'MITIGATION_CATALOGUE_IMPORT';
export const MITIGATION_CATALOGUE_BULK_DELETE = 'MITIGATION_CATALOGUE_BULK_DELETE';

export default {
    fetchAll: MITIGATION_CATALOGUE_FETCH_ALL,
    clear: MITIGATION_CATALOGUE_CLEAR,
    create: MITIGATION_CATALOGUE_CREATE,
    update: MITIGATION_CATALOGUE_UPDATE,
    delete: MITIGATION_CATALOGUE_DELETE,
    bulkDelete: MITIGATION_CATALOGUE_BULK_DELETE,
    bootstrap: MITIGATION_CATALOGUE_BOOTSTRAP,
    fetchById: MITIGATION_CATALOGUE_FETCH_BY_ID,
    export: MITIGATION_CATALOGUE_EXPORT,
    import: MITIGATION_CATALOGUE_IMPORT,
};
