export const STANDARDS_FETCH = 'STANDARDS_FETCH';
export const STANDARDS_SET = 'STANDARDS_SET';
export const STANDARDS_CLEAR = 'STANDARDS_CLEAR';
export const STANDARDS_CREATE = 'STANDARDS_CREATE';

export default {
    fetch: STANDARDS_FETCH,
    set: STANDARDS_SET,
    clear: STANDARDS_CLEAR,
    create: STANDARDS_CREATE
};
