

export const TEMPLATE_FETCH_ALL = 'TEMPLATE_FETCH_ALL';
export const TEMPLATE_FETCH_BY_ID = 'TEMPLATE_FETCH_BY_ID';
export const TEMPLATE_SET_FILTERS = 'TEMPLATE_SET_FILTERS';
export const TEMPLATE_CLEAR = 'TEMPLATE_CLEAR';
export const TEMPLATE_CREATE = 'TEMPLATE_CREATE';
export const TEMPLATE_UPDATE = 'TEMPLATE_UPDATE';
export const TEMPLATE_DELETE = 'TEMPLATE_DELETE';
export const TEMPLATE_FETCH_MODEL_BY_ID = 'TEMPLATE_FETCH_MODEL_BY_ID';
export const TEMPLATE_SET_CONTEXT = 'TEMPLATE_SET_CONTEXT';
export const TEMPLATE_CLEAR_CONTEXT = 'TEMPLATE_CLEAR_CONTEXT';
export const TEMPLATE_SET_LOCAL_DATA = 'TEMPLATE_SET_LOCAL_DATA';
export const TEMPLATE_CLEAR_LOCAL_DATA = 'TEMPLATE_CLEAR_LOCAL_DATA';
export const TEMPLATE_SET_TEMPLATES = 'TEMPLATE_SET_TEMPLATES';
export const TEMPLATE_SET_PAGINATION = 'TEMPLATE_SET_PAGINATION';
export const TEMPLATE_SET_SELECTED = 'TEMPLATE_SET_SELECTED';
export const TEMPLATE_BOOTSTRAP = 'TEMPLATE_BOOTSTRAP';
export const TEMPLATE_SET_CONTENT_REPO_STATUS = 'TEMPLATE_SET_CONTENT_REPO_STATUS';

export default {
    fetchAll: TEMPLATE_FETCH_ALL,
    fetchById: TEMPLATE_FETCH_BY_ID,
    setFilters: TEMPLATE_SET_FILTERS,
    clear: TEMPLATE_CLEAR,
    create: TEMPLATE_CREATE,
    update: TEMPLATE_UPDATE,
    delete: TEMPLATE_DELETE,
    fetchModelById: TEMPLATE_FETCH_MODEL_BY_ID,
    setTemplateContext: TEMPLATE_SET_CONTEXT,
    clearTemplateContext: TEMPLATE_CLEAR_CONTEXT,
    setLocalTemplateData: TEMPLATE_SET_LOCAL_DATA,
    clearLocalTemplateData: TEMPLATE_CLEAR_LOCAL_DATA,
    bootstrap: TEMPLATE_BOOTSTRAP,
    setContentRepoStatus: TEMPLATE_SET_CONTENT_REPO_STATUS
};