

export const TEMPLATE_FETCH_ALL = 'TEMPLATE_FETCH_ALL';
export const TEMPLATE_FETCH_BY_ID = 'TEMPLATE_FETCH_BY_ID';
export const TEMPLATE_SET_FILTERS = 'TEMPLATE_SET_FILTERS'; 
export const TEMPLATE_CLEAR = 'TEMPLATE_CLEAR';

export default {
    fetchAll: TEMPLATE_FETCH_ALL,
    fetchById: TEMPLATE_FETCH_BY_ID,
    setFilters: TEMPLATE_SET_FILTERS, 
    clear: TEMPLATE_CLEAR
};