export const TEMPLATE_FETCH_ALL = 'TEMPLATE_FETCH_ALL';
export const TEMPLATE_FETCH_BY_ID = 'TEMPLATE_FETCH_BY_ID';
export const TEMPLATE_CREATE = 'TEMPLATE_CREATE';
export const TEMPLATE_UPDATE = 'TEMPLATE_UPDATE';
export const TEMPLATE_DELETE = 'TEMPLATE_DELETE';
export const TEMPLATE_SET_FILTERS = 'TEMPLATE_SET_FILTERS';

export default {
    fetchAll: TEMPLATE_FETCH_ALL,
    fetchById: TEMPLATE_FETCH_BY_ID,
    create: TEMPLATE_CREATE,
    update: TEMPLATE_UPDATE,
    delete: TEMPLATE_DELETE,
    setFilters: TEMPLATE_SET_FILTERS,
};
