export const THREAT_CATALOGUE_FETCH_ALL = 'THREAT_CATALOGUE_FETCH_ALL';
export const THREAT_CATALOGUE_FETCH_BY_ID = 'THREAT_CATALOGUE_FETCH_BY_ID';
export const THREAT_CATALOGUE_CLEAR = 'THREAT_CATALOGUE_CLEAR';
export const THREAT_CATALOGUE_CREATE = 'THREAT_CATALOGUE_CREATE';
export const THREAT_CATALOGUE_UPDATE = 'THREAT_CATALOGUE_UPDATE';
export const THREAT_CATALOGUE_DELETE = 'THREAT_CATALOGUE_DELETE';
export const THREAT_CATALOGUE_BOOTSTRAP = 'THREAT_CATALOGUE_BOOTSTRAP';
export const THREAT_CATALOGUE_SET_THREATS = 'THREAT_CATALOGUE_SET_THREATS';
export const THREAT_CATALOGUE_SET_STORE_STATUS = 'THREAT_CATALOGUE_SET_STORE_STATUS';

export default {
    fetchAll: THREAT_CATALOGUE_FETCH_ALL,
    clear: THREAT_CATALOGUE_CLEAR,
    create: THREAT_CATALOGUE_CREATE,
    update: THREAT_CATALOGUE_UPDATE,
    delete: THREAT_CATALOGUE_DELETE,
    bootstrap: THREAT_CATALOGUE_BOOTSTRAP,
    fetchById: THREAT_CATALOGUE_FETCH_BY_ID

};
